### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by n-ce** [abport/color_palette_extractor#1]
1. Insane computational usage
2. shows all pixels instead of sorted most prominent ones

**Comment by abport** [comment]
> 1. Insane computational usage
> 2. shows all pixels instead of sorted most prominent ones

Thank you for bringing this issue to my attention. I have updated the code to use the Color Thief library for color palette extraction instead of the previous implementation. This library is widely used and well-maintained, ensuring accurate and efficient color extraction. I appreciate your feedback and hope this update resolves the issue you encountered. Please let me know if you have any further feedback or concerns.
